Category.create(name: 'Kitchen')
Category.create(name: 'Outdoor')
Category.create(name: 'Bathroom')
Category.create(name: 'Decor')
Category.create(name: 'Entertainment')
User.create(email: 'tanzjacob@gmail.com', password: 'password')